// * MODULARITY =>> HAS A LOT OF BENEFITS [MAINTAINABILITY , REUSABILITY, ABSTRACT]

//* COMMON JS  MODULES

// * MODULARITY =>> HAS A LOT OF BENEFITS [MAINTAINABILITY , REUSABILITY, ABSTRACT]
//* COMMON JS  MODULES

const Circle = require('./circle')
const c = new Circle(10)
console.log(c.draw())
